### ISSUE TITLE
Model registry requires installing all the dependencies at once

### ISSUE THREAD

**Issue by hrnn** [landing-ai/vision-agent-tools#47]
I recently encountered an issue with the `vision-agent-tools` library.

In my current project, I only need the `owlv2` model. Previously, I achieved this by installing the dependency with the `extras` option in my `toml` file:

```toml
vision-agent-tools = {
  git = "git+ssh://git@github.com/landing-ai/vision-agent-tools.git",
  extras = [ "owlv2" ] }
```

Then, in my Python code, I could access the model like this:

```python
...
self._detector = TextToObjectDetection(model=TextToObjectDetectionModel.OWLV2)
...
```

However, after a recent update, installing only `owlv2` caused dependency issues. I started seeing errors like `"qrreader is not installed"`.

The Model Manager currently imports all models at once.

https://github.com/landing-ai/vision-agent-tools/blob/432c17c5871fb363717ca69e185ff3c43bdca0c0/vision_agent_tools/models/model_registry.py#L3-L11

therefore, I'm forced to install everything, `all`, like 

```toml
vision-agent-tools = {
  git = "git+ssh://git@github.com/landing-ai/vision-agent-tools.git",
  extras = [ "all", ] }
```

To avoid potential dependency conflicts between models, I propose updating the Model Registry to use lazy loading.

This approach would only import the necessary models when they are explicitly requested, improving efficiency and preventing unnecessary dependencies.

What are your thoughts on this suggestion?
